spring.application.name=notification-service
server.port=8081

# ========== Kafka Config ==========
kafka.bootstrap-servers=${KAFKA_SERVER_HOSTNAME}
kafka.consumer.group-id=notification-service-group
kafka.consumer.concurrency=1

# ========== Spring Hibernate =============
spring.datasource.url=${DATABASE_USER_DB_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=${DATABASE_DRIVER}
spring.jpa.database-platform=${DATABASE_DIALECT}
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#=========== Channel Configs ================
notification.defaultConfig.processMode=SYNC
notification.dispatcherTopic=notification-dispatcher
notification.inboundTopic=notification-inbound
notification.eventInboxTopic=notification-event-inbox
notification.channelVerificationTopic=notification-channel-verification

notification.channels.SMS.processMode=SYNC
notification.channels.SMS.topic=notification-sms
notification.channels.SMS.url=http://192.168.1.7:8080/api/send
notification.channels.SMS.apiKey=api-key

notification.channels.EMAIL.processMode=SYNC
notification.channels.EMAIL.topic=notification-email
notification.channels.EMAIL.url=http://localhost:8080/api/send
notification.channels.EMAIL.apiKey=api-key

notification.channels.WHATSAPP.processMode=SYNC
notification.channels.WHATSAPP.topic=notification-whatsapp
notification.channels.WHATSAPP.url=http://localhost:8080/api/send
notification.channels.WHATSAPP.apiKey=api-key

notification.channels.PUSH.processMode=SYNC
notification.channels.PUSH.topic=notification-push
notification.channels.PUSH.url=http://localhost:8080/api/send
notification.channels.PUSH.apiKey=api-key